spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:mydb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:tcrmdb;MODE=MYSQL;IGNORECASE=TRUE;INIT=RUNSCRIPT FROM 'src/test/resources/sql/test_sch.sql'\;RUNSCRIPT FROM 'src/test/resources/sql/test_const.sql'\;RUNSCRIPT FROM 'src/test/resources/sql/test_data.sql'
    #url: jdbc:h2:file:C:/Study/db/ldb;MODE=MYSQL;IGNORECASE=TRUE;INIT=RUNSCRIPT FROM 'src/test/resources/sql/test_sch.sql'\;RUNSCRIPT FROM 'src/test/resources/sql/test_const.sql'\;RUNSCRIPT FROM 'src/test/resources/sql/test_data.sql'
    username: sa
    password:
  jpa:
      hibernate:
        ddl-auto: create

