spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:mydb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:C:/Study/db/ldb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
      hibernate:
        ddl-auto: none
